id: I373CDC88
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T23:32:00+00:00'
last_modified: '2022-06-08T05:22:26.140048+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22709
  title: གངས་རི་ཏི་སེའི་དང་མཚོ་ཆེན་མ་དྲོས་ཀྱི་གནས་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E642:
      image_group_id: I1PD96717
      title: ''
      total_pages: 128
      order: 1
      base_file: E642.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
