id: I373CDC88
legacy_id: P005623
ocr_import_info:
  bdrc_scan_id: W22709
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T23:31:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T00:51:09.702098+00:00'
last_modified: 2022-09-02 08:51:16.461072
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22709
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22709
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གངས་རི་ཏི་སེའི་དང་མཚོ་ཆེན་མ་དྲོས་ཀྱི་གནས་བཤད།
  author: འབྲི་གུང་ཆུང་ཚང ༠༦་ཆོས་ཀྱི་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.5034375514764908
  ocr_word_median_confidence_index: 0.4300000071525574
quality: null
bases:
  I1PD96717:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96717
      total_pages: 128
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD96717.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.5034375514764908
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
