id: P005623
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:07:53.196261
source_metadata:
  id: bdr:W22709
  title: གངས་རི་ཏི་སེའི་དང་མཚོ་ཆེན་མ་དྲོས་ཀྱི་གནས་བཤད
  author: ''
  volumes:
    cc617c3471d64055964207bff5d2d0bb:
      image_group_id: I1PD96717
      title: ''
      volume_number: 1
      total_pages: 128
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
